In [1]:
import os
import pandas as pd
import json
from pathlib import Path

## **Section-01**: Data Integrity Check

In [2]:
DATASET_ROOT = "/kaggle/input/datasets/ajfaisal002/crossmodal-misleading-video-dataset"

TRAIN_META_PATH = f"{DATASET_ROOT}/extracted_text/train_metadata.csv"
TEST_META_PATH = f"{DATASET_ROOT}/extracted_text/test_metadata.csv"

TRAIN_FRAME_PATH = f"{DATASET_ROOT}/extracted_frames/train"
TEST_FRAME_PATH = f"{DATASET_ROOT}/extracted_frames/test"

TRAIN_ANNOT_PATH = f"{DATASET_ROOT}/annotations/train_annotations.json"
TEST_ANNOT_PATH = f"{DATASET_ROOT}/annotations/test_annotations.json"

In [3]:
train_meta = pd.read_csv(TRAIN_META_PATH)
test_meta = pd.read_csv(TEST_META_PATH)

print("Train samples:", len(train_meta))
print("Test samples:", len(test_meta))

train_meta.head()

Train samples: 1600
Test samples: 800

,video_id,has_audio,transcript,ocr_text,category,subcategory
0,IF_001,True,আপনি সিদ্ধান্ত নিয়েছেন একটি নতুন অ্যাপ্লিকেশন...,OR EVEN TAKA ON YOUR FIRST CRAZY TIME,misleading,identity_fabrication
1,IF_002,True,"With a small investment of 30,500 Bangladeshi ...",YES WITH A SMALL INVESTMENT OF BANGLADESH TAKA...,misleading,identity_fabrication
2,IF_003,True,"If they close this page, they can't come back ...",IF THEY CLOSE THIS PAGE AS WILL THEIR CHANCE T...,misleading,identity_fabrication
3,IF_004,True,We tested our product with a small group of vo...,AND EACH OF THEM EARNED OVER BANGLADESHI TAKA ...,misleading,identity_fabrication
4,IF_005,True,I am ready to give you your money back from my...,MONEY BACK FROM MY POCKET BANGLADESHI TAKA,misleading,identity_fabrication

In [4]:
print("\nTrain Category Distribution")
print(train_meta["category"].value_counts())

print("\nTrain Subcategory Distribution")
print(train_meta["subcategory"].value_counts())

Train Category Distribution
category
misleading    800
safe          800
Name: count, dtype: int64

Train Subcategory Distribution
subcategory
identity_fabrication                200
perception_manipulation             200
scientifically_unrealistic_scene    200
surreal_content                     200
Name: count, dtype: int64

In [5]:
frame_root = Path(TRAIN_FRAME_PATH)

sample_video = train_meta.iloc[0]["video_id"]

sample_frame_dir = frame_root / sample_video

frames = list(sample_frame_dir.glob("*.jpg"))

print("Sample video:", sample_video)
print("Frame count:", len(frames))
print("Example frame:", frames[0])

Sample video: IF_001
Frame count: 16
Example frame: /kaggle/input/datasets/ajfaisal002/crossmodal-misleading-video-dataset/extracted_frames/train/IF_001/frame_10.jpg

In [6]:
import random

sample_ids = random.sample(list(train_meta["video_id"]), 5)

for vid in sample_ids:
    
    frame_dir = Path(TRAIN_FRAME_PATH) / vid
    frame_count = len(list(frame_dir.glob("*.jpg")))
    
    print(f"{vid} -> {frame_count} frames")

SUS_106 -> 16 frames
SAFE_154 -> 16 frames
IF_045 -> 16 frames
SAFE_129 -> 16 frames
SAFE_529 -> 16 frames

In [7]:
train_meta[["video_id", "has_audio", "transcript"]].head(10)

  video_id  has_audio                                         transcript
0   IF_001       True  আপনি সিদ্ধান্ত নিয়েছেন একটি নতুন অ্যাপ্লিকেশন...
1   IF_002       True  With a small investment of 30,500 Bangladeshi ...
2   IF_003       True  If they close this page, they can't come back ...
3   IF_004       True  We tested our product with a small group of vo...
4   IF_005       True  I am ready to give you your money back from my...
5   IF_006       True  So far, there has not been a single person who...
6   IF_007       True  I've decided to create a new application, Craz...
7   IF_008      False                                                NaN
8   IF_009       True                     We the people stand united now
9   IF_010      False                                                NaN

In [8]:
train_meta[["video_id", "ocr_text"]].head(10)

  video_id                                           ocr_text
0   IF_001              OR EVEN TAKA ON YOUR FIRST CRAZY TIME
1   IF_002  YES WITH A SMALL INVESTMENT OF BANGLADESH TAKA...
2   IF_003  IF THEY CLOSE THIS PAGE AS WILL THEIR CHANCE T...
3   IF_004  AND EACH OF THEM EARNED OVER BANGLADESHI TAKA ...
4   IF_005         MONEY BACK FROM MY POCKET BANGLADESHI TAKA
5   IF_006  NO SPECIAL SKILLS ARE REQUIRED IF THEY WATCH T...
6   IF_007  MANY PLAYERS HAVE BOUGHT CARS AND HOUSES FOR T...
7   IF_008                                                NaN
8   IF_009       WE THE PEOPLE STAND NO NO KINGS NO KING S NO
9   IF_010                                                NaN

In [9]:
with open(TRAIN_ANNOT_PATH) as f:
    train_annotations = json.load(f)

with open(TEST_ANNOT_PATH) as f:
    test_annotations = json.load(f)

print("Train annotations:", len(train_annotations))
print("Test annotations:", len(test_annotations))

Train annotations: 1600
Test annotations: 800

In [10]:
print(train_annotations[0])


print(train_annotations[956])

{'video_id': 'IF_001', 'category': 'misleading', 'subcategory': 'identity_fabrication', 'audio_available': True, 'visual_description': 'An elderly man with gray hair is seated on an ornate white carved chair, speaking directly toward the camera. The background features wooden interior decor. The scene remains static, and subtitle-style text appears at the bottom of the screen.', 'audio_transcript': "I've decided to create a new application. Crazy time. By investing just 5 taka, you can win 50,000 or even 100,000 taka on your first day.", 'ocr_text': ['due to the current crisis in the country', "I've decided to create a new application", 'crazy time', 'by investing just 5 taka you can win 50,000'], 'scene_summary': 'A man appears to be giving an announcement while subtitles promote a financial scheme claiming that a 5-taka investment can generate 50,000–100,000 taka. These claims are unrealistic and represent deceptive financial misinformation.', 'explanation': {'visual_cues': 'Static interview-style scene with a speaker delivering a message, paired with clearly edited subtitle overlays.', 'audio_cues': 'The spoken dialogue itself includes promises of extremely high returns for very small investments, which is a common indicator of financial scams.', 'text_cues': "OCR text and the transcript both contain unrealistic claims such as 'win 50,000 or 100,000 taka on your first day'.", 'overall_reason': 'The video is classified as a False Claim because it contains deceptive financial promises that violate common economic logic and match known characteristics of fraudulent schemes.'}}
{'video_id': 'SAFE_157', 'category': 'safe', 'audio_available': True, 'visual_description': 'A teacher speaks to students while one student raises a hand, showing engagement.', 'audio_transcript': '[tone: calm] Honesty builds trust.', 'ocr_text': ['Honesty builds trust.'], 'scene_summary': 'A teacher explains the importance of honesty in a positive classroom discussion.', 'explanation': {'visual_cues': 'Encouraging teacher expression and student participation.', 'audio_cues': 'Clear and calm educational statement.', 'text_cues': 'Caption matches the lesson being taught.', 'overall_reason': 'The clip teaches a universal moral value in a safe and non-deceptive way.'}}

In [11]:
print("\nDATASET SUMMARY")
print("--------------")

print("Train Videos:", len(train_meta))
print("Test Videos:", len(test_meta))

print("Train Annotations:", len(train_annotations))
print("Test Annotations:", len(test_annotations))

print("\nDataset integrity check completed successfully.")

DATASET SUMMARY
--------------
Train Videos: 1600
Test Videos: 800
Train Annotations: 1600
Test Annotations: 800

Dataset integrity check completed successfully.